parser: "babel-eslint"

parserOptions:
  sourceType: module
  ecmaFeatures:
    modules: true
    jsx: true
    experimentalObjectRestSpread: true

extends:
  - airbnb
  - plugin:flowtype/recommended
  - prettier
  - prettier/flowtype
  - prettier/react

plugins:
  - prettier
  - flowtype

settings:
  import/resolver: webpack
  flowtype:
    onlyFilesWithFlowAnnotation: true

env:
  es6: true
  node: true
  browser: true

rules:
  prettier/prettier:
    - error
    - printWidth: 80
      tabWidth: 2
      semi: true
      trailingComma: all
      bracketSpacing: true
      jsxBracketSameLine: false
      singleQuote: true
      parser: flow

  no-plusplus: off
  no-shadow: off
  no-restricted-globals: off
  func-names: off
  linebreak-style: [off] # rule still works with `linebreak-style: off`
  no-implicit-coercion: error
  padding-line-between-statements:
    - error
    - blankLine: always
      prev: [const, let, var]
      next: "*" 
    - blankLine: always
      prev: "*"
      next: [const, let, var]
    - blankLine: any
      prev: [const, let, var]
      next: [const, let, var]
    - blankLine: always
      prev: "*"
      next: return
    - blankLine: always
      prev: "*"
      next: [case, default]
    - blankLine: always
      prev: [const, let, var, block, block-like]
      next: [block, block-like]
    - blankLine: always
      prev: directive
      next: "*"
    - blankLine: any
      prev: directive
      next: directive

  jsx-a11y/anchor-is-valid:
    - warn
    - components: [Link]
      specialLink: [to]
      aspects: [noHref, invalidHref, preferButton]
      
  jsx-a11y/label-has-for:
    - warn
    - components: [label]
      required: 
        some: [ nesting, id ]

  jsx-a11y/no-noninteractive-element-to-interactive-role: error
  jsx-a11y/img-redundant-alt: off
  jsx-a11y/click-events-have-key-events: off

  import/no-named-as-default: off
  import/newline-after-import: error

  react/jsx-filename-extension: off
  react/require-default-props: off
  react/prefer-stateless-function: error
  react/no-unused-prop-types: warn
  react/no-find-dom-node: error
  react/default-props-match-prop-types: off # rule break linting in case of invalid declaration
                                            # very difficult to detect problem so just turn it off
